/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.yqm.wapiti4j.wrapper;

public class dat_s {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected dat_s(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(dat_s obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pywapitiJNI.delete_dat_s(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setLbl(boolean value) {
    pywapitiJNI.dat_s_lbl_set(swigCPtr, this, value);
  }

  public boolean getLbl() {
    return pywapitiJNI.dat_s_lbl_get(swigCPtr, this);
  }

  public void setMlen(long value) {
    pywapitiJNI.dat_s_mlen_set(swigCPtr, this, value);
  }

  public long getMlen() {
    return pywapitiJNI.dat_s_mlen_get(swigCPtr, this);
  }

  public void setNseq(long value) {
    pywapitiJNI.dat_s_nseq_set(swigCPtr, this, value);
  }

  public long getNseq() {
    return pywapitiJNI.dat_s_nseq_get(swigCPtr, this);
  }

  public void setSeq(SWIGTYPE_p_p_seq_s value) {
    pywapitiJNI.dat_s_seq_set(swigCPtr, this, SWIGTYPE_p_p_seq_s.getCPtr(value));
  }

  public SWIGTYPE_p_p_seq_s getSeq() {
    long cPtr = pywapitiJNI.dat_s_seq_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_seq_s(cPtr, false);
  }

  public dat_s() {
    this(pywapitiJNI.new_dat_s(), true);
  }

}
