/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.yqm.wapiti4j.wrapper;

public class mdl_s {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected mdl_s(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(mdl_s obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pywapitiJNI.delete_mdl_s(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setOpt(opt_s value) {
    pywapitiJNI.mdl_s_opt_set(swigCPtr, this, opt_s.getCPtr(value), value);
  }

  public opt_s getOpt() {
    long cPtr = pywapitiJNI.mdl_s_opt_get(swigCPtr, this);
    return (cPtr == 0) ? null : new opt_s(cPtr, false);
  }

  public void setType(int value) {
    pywapitiJNI.mdl_s_type_set(swigCPtr, this, value);
  }

  public int getType() {
    return pywapitiJNI.mdl_s_type_get(swigCPtr, this);
  }

  public void setNlbl(long value) {
    pywapitiJNI.mdl_s_nlbl_set(swigCPtr, this, value);
  }

  public long getNlbl() {
    return pywapitiJNI.mdl_s_nlbl_get(swigCPtr, this);
  }

  public void setNobs(long value) {
    pywapitiJNI.mdl_s_nobs_set(swigCPtr, this, value);
  }

  public long getNobs() {
    return pywapitiJNI.mdl_s_nobs_get(swigCPtr, this);
  }

  public void setNftr(long value) {
    pywapitiJNI.mdl_s_nftr_set(swigCPtr, this, value);
  }

  public long getNftr() {
    return pywapitiJNI.mdl_s_nftr_get(swigCPtr, this);
  }

  public void setKind(String value) {
    pywapitiJNI.mdl_s_kind_set(swigCPtr, this, value);
  }

  public String getKind() {
    return pywapitiJNI.mdl_s_kind_get(swigCPtr, this);
  }

  public void setUoff(SWIGTYPE_p_unsigned_long value) {
    pywapitiJNI.mdl_s_uoff_set(swigCPtr, this, SWIGTYPE_p_unsigned_long.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_long getUoff() {
    long cPtr = pywapitiJNI.mdl_s_uoff_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_long(cPtr, false);
  }

  public void setBoff(SWIGTYPE_p_unsigned_long value) {
    pywapitiJNI.mdl_s_boff_set(swigCPtr, this, SWIGTYPE_p_unsigned_long.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_long getBoff() {
    long cPtr = pywapitiJNI.mdl_s_boff_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_long(cPtr, false);
  }

  public void setTheta(SWIGTYPE_p_double value) {
    pywapitiJNI.mdl_s_theta_set(swigCPtr, this, SWIGTYPE_p_double.getCPtr(value));
  }

  public SWIGTYPE_p_double getTheta() {
    long cPtr = pywapitiJNI.mdl_s_theta_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_double(cPtr, false);
  }

  public void setTrain(dat_s value) {
    pywapitiJNI.mdl_s_train_set(swigCPtr, this, dat_s.getCPtr(value), value);
  }

  public dat_s getTrain() {
    long cPtr = pywapitiJNI.mdl_s_train_get(swigCPtr, this);
    return (cPtr == 0) ? null : new dat_s(cPtr, false);
  }

  public void setDevel(dat_s value) {
    pywapitiJNI.mdl_s_devel_set(swigCPtr, this, dat_s.getCPtr(value), value);
  }

  public dat_s getDevel() {
    long cPtr = pywapitiJNI.mdl_s_devel_get(swigCPtr, this);
    return (cPtr == 0) ? null : new dat_s(cPtr, false);
  }

  public void setReader(rdr_s value) {
    pywapitiJNI.mdl_s_reader_set(swigCPtr, this, rdr_s.getCPtr(value), value);
  }

  public rdr_s getReader() {
    long cPtr = pywapitiJNI.mdl_s_reader_get(swigCPtr, this);
    return (cPtr == 0) ? null : new rdr_s(cPtr, false);
  }

  public void setWerr(SWIGTYPE_p_double value) {
    pywapitiJNI.mdl_s_werr_set(swigCPtr, this, SWIGTYPE_p_double.getCPtr(value));
  }

  public SWIGTYPE_p_double getWerr() {
    long cPtr = pywapitiJNI.mdl_s_werr_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_double(cPtr, false);
  }

  public void setWcnt(long value) {
    pywapitiJNI.mdl_s_wcnt_set(swigCPtr, this, value);
  }

  public long getWcnt() {
    return pywapitiJNI.mdl_s_wcnt_get(swigCPtr, this);
  }

  public void setWpos(long value) {
    pywapitiJNI.mdl_s_wpos_set(swigCPtr, this, value);
  }

  public long getWpos() {
    return pywapitiJNI.mdl_s_wpos_get(swigCPtr, this);
  }

  public void setTimer(SWIGTYPE_p_timeval value) {
    pywapitiJNI.mdl_s_timer_set(swigCPtr, this, SWIGTYPE_p_timeval.getCPtr(value));
  }

  public SWIGTYPE_p_timeval getTimer() {
    return new SWIGTYPE_p_timeval(pywapitiJNI.mdl_s_timer_get(swigCPtr, this), true);
  }

  public void setTotal(double value) {
    pywapitiJNI.mdl_s_total_set(swigCPtr, this, value);
  }

  public double getTotal() {
    return pywapitiJNI.mdl_s_total_get(swigCPtr, this);
  }

  public mdl_s() {
    this(pywapitiJNI.new_mdl_s(), true);
  }

}
