/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.yqm.wapiti4j.wrapper;

public class opt_s_lbfgs {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected opt_s_lbfgs(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(opt_s_lbfgs obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pywapitiJNI.delete_opt_s_lbfgs(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setClip(boolean value) {
    pywapitiJNI.opt_s_lbfgs_clip_set(swigCPtr, this, value);
  }

  public boolean getClip() {
    return pywapitiJNI.opt_s_lbfgs_clip_get(swigCPtr, this);
  }

  public void setHistsz(long value) {
    pywapitiJNI.opt_s_lbfgs_histsz_set(swigCPtr, this, value);
  }

  public long getHistsz() {
    return pywapitiJNI.opt_s_lbfgs_histsz_get(swigCPtr, this);
  }

  public void setMaxls(long value) {
    pywapitiJNI.opt_s_lbfgs_maxls_set(swigCPtr, this, value);
  }

  public long getMaxls() {
    return pywapitiJNI.opt_s_lbfgs_maxls_get(swigCPtr, this);
  }

  public opt_s_lbfgs() {
    this(pywapitiJNI.new_opt_s_lbfgs(), true);
  }

}
