/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.yqm.wapiti4j.wrapper;

public class opt_s_bcd {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected opt_s_bcd(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(opt_s_bcd obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pywapitiJNI.delete_opt_s_bcd(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setKappa(double value) {
    pywapitiJNI.opt_s_bcd_kappa_set(swigCPtr, this, value);
  }

  public double getKappa() {
    return pywapitiJNI.opt_s_bcd_kappa_get(swigCPtr, this);
  }

  public opt_s_bcd() {
    this(pywapitiJNI.new_opt_s_bcd(), true);
  }

}
