/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.yqm.wapiti4j.wrapper;

public class opt_s_rprop {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected opt_s_rprop(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(opt_s_rprop obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pywapitiJNI.delete_opt_s_rprop(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setStpmin(double value) {
    pywapitiJNI.opt_s_rprop_stpmin_set(swigCPtr, this, value);
  }

  public double getStpmin() {
    return pywapitiJNI.opt_s_rprop_stpmin_get(swigCPtr, this);
  }

  public void setStpmax(double value) {
    pywapitiJNI.opt_s_rprop_stpmax_set(swigCPtr, this, value);
  }

  public double getStpmax() {
    return pywapitiJNI.opt_s_rprop_stpmax_get(swigCPtr, this);
  }

  public void setStpinc(double value) {
    pywapitiJNI.opt_s_rprop_stpinc_set(swigCPtr, this, value);
  }

  public double getStpinc() {
    return pywapitiJNI.opt_s_rprop_stpinc_get(swigCPtr, this);
  }

  public void setStpdec(double value) {
    pywapitiJNI.opt_s_rprop_stpdec_set(swigCPtr, this, value);
  }

  public double getStpdec() {
    return pywapitiJNI.opt_s_rprop_stpdec_get(swigCPtr, this);
  }

  public void setCutoff(boolean value) {
    pywapitiJNI.opt_s_rprop_cutoff_set(swigCPtr, this, value);
  }

  public boolean getCutoff() {
    return pywapitiJNI.opt_s_rprop_cutoff_get(swigCPtr, this);
  }

  public opt_s_rprop() {
    this(pywapitiJNI.new_opt_s_rprop(), true);
  }

}
