/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.yqm.wapiti4j.wrapper;

public class raw_s {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected raw_s(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(raw_s obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pywapitiJNI.delete_raw_s(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setLen(long value) {
    pywapitiJNI.raw_s_len_set(swigCPtr, this, value);
  }

  public long getLen() {
    return pywapitiJNI.raw_s_len_get(swigCPtr, this);
  }

  public SWIGTYPE_p_p_char getLines() {
    long cPtr = pywapitiJNI.raw_s_lines_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_char(cPtr, false);
  }

  public raw_s() {
    this(pywapitiJNI.new_raw_s(), true);
  }

}
