/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.yqm.wapiti4j.wrapper;

public class rdr_s {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected rdr_s(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(rdr_s obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pywapitiJNI.delete_rdr_s(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setAutouni(boolean value) {
    pywapitiJNI.rdr_s_autouni_set(swigCPtr, this, value);
  }

  public boolean getAutouni() {
    return pywapitiJNI.rdr_s_autouni_get(swigCPtr, this);
  }

  public void setNpats(long value) {
    pywapitiJNI.rdr_s_npats_set(swigCPtr, this, value);
  }

  public long getNpats() {
    return pywapitiJNI.rdr_s_npats_get(swigCPtr, this);
  }

  public void setNuni(long value) {
    pywapitiJNI.rdr_s_nuni_set(swigCPtr, this, value);
  }

  public long getNuni() {
    return pywapitiJNI.rdr_s_nuni_get(swigCPtr, this);
  }

  public void setNbi(long value) {
    pywapitiJNI.rdr_s_nbi_set(swigCPtr, this, value);
  }

  public long getNbi() {
    return pywapitiJNI.rdr_s_nbi_get(swigCPtr, this);
  }

  public void setNtoks(long value) {
    pywapitiJNI.rdr_s_ntoks_set(swigCPtr, this, value);
  }

  public long getNtoks() {
    return pywapitiJNI.rdr_s_ntoks_get(swigCPtr, this);
  }

  public void setPats(SWIGTYPE_p_p_pat_t value) {
    pywapitiJNI.rdr_s_pats_set(swigCPtr, this, SWIGTYPE_p_p_pat_t.getCPtr(value));
  }

  public SWIGTYPE_p_p_pat_t getPats() {
    long cPtr = pywapitiJNI.rdr_s_pats_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_pat_t(cPtr, false);
  }

  public void setLbl(SWIGTYPE_p_qrk_s value) {
    pywapitiJNI.rdr_s_lbl_set(swigCPtr, this, SWIGTYPE_p_qrk_s.getCPtr(value));
  }

  public SWIGTYPE_p_qrk_s getLbl() {
    long cPtr = pywapitiJNI.rdr_s_lbl_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_qrk_s(cPtr, false);
  }

  public void setObs(SWIGTYPE_p_qrk_s value) {
    pywapitiJNI.rdr_s_obs_set(swigCPtr, this, SWIGTYPE_p_qrk_s.getCPtr(value));
  }

  public SWIGTYPE_p_qrk_s getObs() {
    long cPtr = pywapitiJNI.rdr_s_obs_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_qrk_s(cPtr, false);
  }

  public rdr_s() {
    this(pywapitiJNI.new_rdr_s(), true);
  }

}
