/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.yqm.wapiti4j.wrapper;

public class seq_s_pos {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected seq_s_pos(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(seq_s_pos obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pywapitiJNI.delete_seq_s_pos(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setLbl(long value) {
    pywapitiJNI.seq_s_pos_lbl_set(swigCPtr, this, value);
  }

  public long getLbl() {
    return pywapitiJNI.seq_s_pos_lbl_get(swigCPtr, this);
  }

  public void setUcnt(long value) {
    pywapitiJNI.seq_s_pos_ucnt_set(swigCPtr, this, value);
  }

  public long getUcnt() {
    return pywapitiJNI.seq_s_pos_ucnt_get(swigCPtr, this);
  }

  public void setBcnt(long value) {
    pywapitiJNI.seq_s_pos_bcnt_set(swigCPtr, this, value);
  }

  public long getBcnt() {
    return pywapitiJNI.seq_s_pos_bcnt_get(swigCPtr, this);
  }

  public void setUobs(SWIGTYPE_p_unsigned_long value) {
    pywapitiJNI.seq_s_pos_uobs_set(swigCPtr, this, SWIGTYPE_p_unsigned_long.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_long getUobs() {
    long cPtr = pywapitiJNI.seq_s_pos_uobs_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_long(cPtr, false);
  }

  public void setBobs(SWIGTYPE_p_unsigned_long value) {
    pywapitiJNI.seq_s_pos_bobs_set(swigCPtr, this, SWIGTYPE_p_unsigned_long.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_long getBobs() {
    long cPtr = pywapitiJNI.seq_s_pos_bobs_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_long(cPtr, false);
  }

  public seq_s_pos() {
    this(pywapitiJNI.new_seq_s_pos(), true);
  }

}
