/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.yqm.wapiti4j.wrapper;

public class tok_s {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected tok_s(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(tok_s obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pywapitiJNI.delete_tok_s(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setLen(long value) {
    pywapitiJNI.tok_s_len_set(swigCPtr, this, value);
  }

  public long getLen() {
    return pywapitiJNI.tok_s_len_get(swigCPtr, this);
  }

  public void setLbl(SWIGTYPE_p_p_char value) {
    pywapitiJNI.tok_s_lbl_set(swigCPtr, this, SWIGTYPE_p_p_char.getCPtr(value));
  }

  public SWIGTYPE_p_p_char getLbl() {
    long cPtr = pywapitiJNI.tok_s_lbl_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_char(cPtr, false);
  }

  public void setCnts(SWIGTYPE_p_unsigned_int value) {
    pywapitiJNI.tok_s_cnts_set(swigCPtr, this, SWIGTYPE_p_unsigned_int.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_int getCnts() {
    long cPtr = pywapitiJNI.tok_s_cnts_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_int(cPtr, false);
  }

  public SWIGTYPE_p_p_p_char getToks() {
    long cPtr = pywapitiJNI.tok_s_toks_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_p_char(cPtr, false);
  }

  public tok_s() {
    this(pywapitiJNI.new_tok_s(), true);
  }

}
